# Generated by Django 2.1.10 on 2020-01-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0002_sightinfo_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('CommentId', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='评论的ID')),
                ('DistrictId', models.CharField(blank=True, max_length=50, verbose_name='区域的ID')),
                ('POIName', models.CharField(blank=True, max_length=50, verbose_name='景点名字')),
                ('TotalStar', models.CharField(blank=True, max_length=3, verbose_name='用户评分')),
                ('Content', models.TextField(blank=True, verbose_name='评论内容')),
                ('AuditTime', models.CharField(blank=True, max_length=50, verbose_name='评论时间')),
                ('LastModifyTime', models.CharField(blank=True, max_length=50, verbose_name='评论时间')),
                ('Score1', models.CharField(blank=True, max_length=3, verbose_name='景色评分')),
                ('Score2', models.CharField(blank=True, max_length=3, verbose_name='趣味评分')),
                ('Score3', models.CharField(blank=True, max_length=3, verbose_name='性价比评分')),
            ],
            options={
                'verbose_name': '评论详情',
                'verbose_name_plural': '评论详情',
            },
        ),
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordcloud', models.TextField(blank=True, verbose_name='评论词云')),
            ],
            options={
                'verbose_name': '评论词云',
                'verbose_name_plural': '评论词云',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_Id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户的ID')),
                ('user_Nick', models.CharField(blank=True, max_length=50, verbose_name='用户的昵称')),
                ('user_profile_image_url', models.TextField(blank=True, verbose_name='用户的头像')),
                ('user_Gender', models.IntegerField(blank=True, default=0, verbose_name='用户性别')),
                ('user_FriendCount', models.IntegerField(blank=True, default=0, verbose_name='用户关注数')),
                ('user_FollowCount', models.IntegerField(blank=True, default=0, verbose_name='用户粉丝')),
                ('user_CommentCount', models.IntegerField(blank=True, default=0, verbose_name='用户评论数')),
                ('user_DistrictName', models.CharField(blank=True, max_length=50, verbose_name='用户地区')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AlterModelOptions(
            name='sightinfo',
            options={'verbose_name': '景点信息', 'verbose_name_plural': '景点信息'},
        ),
        migrations.RenameField(
            model_name='sightinfo',
            old_name='addressWay',
            new_name='AddressWay',
        ),
        migrations.AddField(
            model_name='imginfo',
            name='SightInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.SightInfo', verbose_name='景点信息'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='SightInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.SightInfo', verbose_name='景点信息'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='UserInfo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.UserInfo', verbose_name='评论用户信息'),
        ),
    ]
