# Generated by Django 2.1.10 on 2020-01-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0003_auto_20200110_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightinfo',
            name='DescriptorText',
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='UserInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.UserInfo', verbose_name='评论用户信息'),
        ),
    ]
