# Generated by Django 2.1.10 on 2020-01-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0004_auto_20200110_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='cookie',
        ),
    ]
