# Generated by Django 2.1.10 on 2020-01-10 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0005_remove_target_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinfo',
            name='crawl_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='pinyin',
            field=models.TextField(blank=True, verbose_name='词性'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='sentiments',
            field=models.CharField(blank=True, max_length=50, verbose_name='情感值'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='tags',
            field=models.TextField(blank=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='CommentId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评论的ID'),
        ),
    ]
