# Generated by Django 2.1.10 on 2020-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0006_auto_20200110_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='sentiments',
            field=models.FloatField(blank=True, default=0, verbose_name='情感值'),
        ),
    ]
