# Generated by Django 2.1.10 on 2020-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0007_auto_20200111_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='LastModifyTime',
            field=models.CharField(blank=True, max_length=50, verbose_name='最后修改时间'),
        ),
    ]
