# Generated by Django 2.1.10 on 2020-04-01 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SightInfo_id', models.CharField(blank=True, max_length=10, verbose_name='景点信息ID')),
                ('AspectWord', models.TextField(blank=True, verbose_name='方面词统计')),
            ],
            options={
                'verbose_name': 'Aspect words',
                'verbose_name_plural': 'Aspect words',
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('UserInfo_id', models.CharField(blank=True, max_length=10, verbose_name='评论用户ID')),
                ('SightInfo_id', models.CharField(blank=True, max_length=10, verbose_name='景点信息ID')),
                ('CommentId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评论的ID')),
                ('DistrictId', models.CharField(blank=True, max_length=50, verbose_name='区域的ID')),
                ('POIName', models.CharField(blank=True, max_length=50, verbose_name='景点名字')),
                ('TotalStar', models.CharField(blank=True, max_length=3, verbose_name='用户评分')),
                ('Content', models.TextField(blank=True, verbose_name='评论内容')),
                ('AuditTime', models.CharField(blank=True, max_length=50, verbose_name='评论时间')),
                ('LastModifyTime', models.CharField(blank=True, max_length=50, verbose_name='最后修改时间')),
                ('Score1', models.CharField(blank=True, max_length=3, verbose_name='景色评分')),
                ('Score2', models.CharField(blank=True, max_length=3, verbose_name='趣味评分')),
                ('Score3', models.CharField(blank=True, max_length=3, verbose_name='性价比评分')),
                ('crawl_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '评论详情',
                'verbose_name_plural': '评论详情',
            },
        ),
        migrations.CreateModel(
            name='SightInfo',
            fields=[
                ('Title', models.CharField(blank=True, max_length=50, verbose_name='名字')),
                ('BusinessId', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='景点id')),
                ('DistrictId', models.IntegerField(default=0, verbose_name='地区id')),
                ('Tags', models.CharField(blank=True, max_length=30, verbose_name='特点')),
                ('Texts', models.CharField(blank=True, max_length=30, verbose_name='排名')),
                ('CommentScoreReal', models.CharField(blank=True, max_length=3, verbose_name='评分')),
                ('CommentNumberText', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('AddressText', models.CharField(blank=True, max_length=50, verbose_name='地点')),
                ('AddressWay', models.CharField(blank=True, max_length=50, verbose_name='到达方式')),
                ('DescriptorText', models.TextField(blank=True, verbose_name='描述信息')),
                ('OpenTimeSubText', models.TextField(blank=True, verbose_name='开放时间')),
                ('Img', models.TextField(blank=True, verbose_name='图片地址')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '景点信息',
                'verbose_name_plural': '景点信息',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, verbose_name='爬取景点id')),
                ('did', models.CharField(max_length=20, verbose_name='景点地区id')),
                ('isScrapy', models.IntegerField(default=0, verbose_name='是否爬取')),
                ('cookie', models.TextField(blank=True, verbose_name='设置cookie')),
                ('group', models.IntegerField(default=0, verbose_name='景点分组')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '爬虫设置',
                'verbose_name_plural': '爬虫设置',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_Id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户的ID')),
                ('user_Nick', models.CharField(blank=True, max_length=50, verbose_name='用户的昵称')),
                ('user_profile_image_url', models.TextField(blank=True, verbose_name='用户的头像')),
                ('user_Gender', models.IntegerField(blank=True, default=0, verbose_name='用户性别')),
                ('user_FriendCount', models.IntegerField(blank=True, default=0, verbose_name='用户关注数')),
                ('user_FollowCount', models.IntegerField(blank=True, default=0, verbose_name='用户粉丝')),
                ('user_CommentCount', models.IntegerField(blank=True, default=0, verbose_name='用户评论数')),
                ('user_DistrictName', models.CharField(blank=True, max_length=50, verbose_name='用户地区')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
