# Generated by Django 2.1.10 on 2020-01-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='cookie',
            field=models.TextField(blank=True, verbose_name='设置cookie'),
        ),
        migrations.AddField(
            model_name='target',
            name='group',
            field=models.IntegerField(default=0, verbose_name='用户分组'),
        ),
        migrations.AddField(
            model_name='target',
            name='isScrapy',
            field=models.IntegerField(default=0, verbose_name='是否爬取'),
        ),
    ]
