# Generated by Django 2.1.10 on 2020-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0002_auto_20200112_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinfo',
            name='pinyin',
        ),
        migrations.RemoveField(
            model_name='commentinfo',
            name='sentiments',
        ),
        migrations.RemoveField(
            model_name='commentinfo',
            name='tags',
        ),
        migrations.AlterField(
            model_name='target',
            name='group',
            field=models.IntegerField(default=0, verbose_name='景点分组'),
        ),
    ]
