# Generated by Django 2.1.10 on 2020-01-12 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0003_auto_20200112_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightinfo',
            name='crawl_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
