# Generated by Django 2.1.10 on 2020-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0004_sightinfo_crawl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightinfo',
            name='AddressText',
            field=models.CharField(blank=True, max_length=50, verbose_name='地点'),
        ),
    ]
