# Generated by Django 2.1.10 on 2020-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0005_auto_20200113_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightinfo',
            name='DescriptorText',
            field=models.TextField(blank=True, verbose_name='描述信息'),
        ),
        migrations.AddField(
            model_name='sightinfo',
            name='OpenTimeSubText',
            field=models.TextField(blank=True, verbose_name='开放时间'),
        ),
    ]
