# Generated by Django 2.1.10 on 2020-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0006_auto_20200113_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinfo',
            name='SightInfo',
        ),
        migrations.RemoveField(
            model_name='commentinfo',
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='SightInfo_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='景点信息ID'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='UserInfo_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='评论用户ID'),
        ),
    ]
